---
# Deploy group-specific udev rules

- name: Deploy USB serial udev rules
  template:
    src: 99-usb-serial.rules.j2
    dest: /etc/udev/rules.d/99-usb-serial.rules
    owner: root
    group: root
    mode: "0644"
  become: yes
  notify: reload udev rules
